### ISSUE TITLE
Add prefixes for slackmoji packs

### ISSUE THREAD

**Issue by gtback** [lambtron/emojipacks#126]
Some ideas to prevent name conflicts between different packs:

- prefix `slackmojis-scrabble-letters.yaml` with `scrabble-`
- prefix `slackmojis-facebook-reaction.yaml` with `fb-`

From https://github.com/lambtron/emojipacks/pull/123#issuecomment-318894509

**Comment by flamableconcrete** [comment]
Here's my first draft. Any comments on the ones in the middle where I haven't decided? I think I lean more on the no prefix side when in question. Except maybe Star Wars? Convince me otherwise or I'll put in a pull request for just the ones below with a definite prefix.

For quick reference: http://slackmojis.com

| Category          | File                                 | Prefix          |
| ----------------- | ------------------------------------ | --------------- |
| MLB               | `slackmojis-mlb.yaml`                | `mlb-`
| NBA               | `slackmojis-nba.yaml`                | `nba-`
| NFL               | `slackmojis-nfl.yaml`                | `nfl-`
| NHL               | `slackmojis-nhl.yaml`                | `nhl-`
| Facebook Reaction | `slackmojis-facebook-reaction.yaml`  | `fb-`
| Scrabble          | `slackmojis-scrabble-letters.yaml`   | `scrabble-`
| Skype             | `slackmojis-skype.yaml`              | `skype-` or none
| NYC Subway        | `slackmojis-nyc-subway.yaml`         | `nyc-` or none
| Star Wars         | `slackmojis-star-wars.yaml`          | `sw-` or none
| Yoyo              | `slackmojis-yoyo.yaml`               | `yoyo-` or none
| Meme              | `slackmojis-meme.yaml`               | `meme-` or none
| Party Parrot      | `slackmojis-party-parrot.yaml`       | none (parrot already in almost all of them!)
| Pokemon           | `slackmojis-pokemon.yaml`            | none
| Uncategorized     | `slackmojis-uncategorized.yaml`      | none
| Logo              | `slackmojis-logo.yaml`               | none
| Retro Game        | `slackmojis-retro-game.yaml`         | none
| Turntable.fm      | `slackmojis-turntable.fm.yaml`       | none

**Comment by gtback** [comment]
I'd also lean towards no prefixes for now on the ones you have as `or none`.

**Comment by zachfeldman** [comment]
Agreed with what's been said so far.

**Comment by gtback** [comment]
Closed by #127
