### ISSUE TITLE
image upload from github seems to have not worked...

### ISSUE THREAD

**Issue by und1sk0** [lambtron/emojipacks#26]
`emojipacks` logs me in and seems to process my yml, but emoji do not show up on the slack team. i can manually add emoji via the web U/I so it doesn't seem to be a permissions thing. sample from the yaml:

`title: ingress`
`emojis:`
`- name: ada`
`src: https://github.com/thekewe/ingress-slack-emoji/blob/master/emoji/ada_emoji.png`
`- name: axa`
`src: https://github.com/thekewe/ingress-slack-emoji/blob/master/emoji/axa_emoji.png`
`- name: capsule`

(etc.. )

output:

`Path or URL of Emoji yaml file: ./ingress.yml`
`Starting import`
`Got tokens`
`Logged in`
`Upload crumb is [redacted]`
`Getting emoji page`
`Uploading ada with https://github.com/thekewe/ingress-slack-emoji/blob/master/emoji/ada_emoji.png`
`Uploading axa with https://github.com/thekewe/ingress-slack-emoji/blob/master/emoji/axa_emoji.png`

**Comment by kphamilton** [comment]
Also happening for me.

**Comment by dshackith** [comment]
Ditto

**Comment by davidcelis** [comment]
This is because `https://github.com/thekewe/ingress-slack-emoji/blob/master/emoji/ada_emoji.png` doesn't actually have a Content-Type of `image/png`; that points to an HTML page that displays the image in GitHub's file view. What you want is the actual raw content:

https://raw.githubusercontent.com/thekewe/ingress-slack-emoji/master/emoji/ada_emoji.png

**Comment by hugovk** [comment]
@und1sk0 Problem isn't with emojipacks but with custom YAML files. This issue can be closed.
